name: docs_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cdsapi
  - xarray
  - cfgrib
  - numpy
  - pandas
  - matplotlib
  - netCDF4
  - shapely
  - geopandas
  - cartopy
  - myst-nb
  - sphinx
  - sphinx-autoapi
  - sphinx_rtd_theme
  - pip:
      - -e .
