name: venv_forecast
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - cdsapi
  - xarray
  - cfgrib
  - pandas
  - matplotlib
  - netCDF4
  - geopandas
  - shapely
  - dask
  - cartopy
  - pytest
  - sphinx
  - sphinx-autoapi
  - myst-nb
  - sphinx_rtd_theme
  - pip
  - pip:
    - -e .. 
    - -r requirements.txt
